user_index :
  path: /user/index
  controller: App\Controller\UserController::index

user_new :
  path: /user/new
  controller: App\Controller\UserController::new

user_edit :
  path: /user/{userId}/edit
  controller: App\Controller\UserController::edit

user_delete :
  path: /user/{userId}/delete
  controller: App\Controller\UserController::delete